### ISSUE TITLE
BearHead component freezing and not displaying BearHead

### ISSUE THREAD

**Issue by jtstrader** [jtstrader/toby-magick#8]
# Current Visual Bug
The application is freezing but only on the BearHead component. Wireframe is functioning fine. This should be priority 1 for now, since it is currently happening on the display in Willet hallway.

No current steps to reproduce this issue, but this issue *has* occurred on my more powerful machine, so I don't believe it's a hardware issue. Need to debug how the frames are animating to make sure a clock isn't misfiring.

**Comment by mwskar** [comment]
Ok. By freezing do you mean the entire thing freezes and is unresponsive? Is it just the bear head that freezes but everything else loads? Can the menu still be accessed?

**Comment by jtstrader** [comment]
It freezes after a few seconds of being on BearHead, and it never displays the BearHead itself. Everything looks accessible, just need to diagnose what's happening.

It also does swap successfully back to Wireframe after freezing. It's like an animation glitch, not the app locking up.

**Comment by jtstrader** [comment]
It's because the app had crashed. We received a "Too many open files" error on attempting to open the toby head file. It's possible that the files are opening but are not closing.
